//! Enumerating a checkout's tracked files and sorting each into one census
//! class: excluded, vendored, generated, eligible or unsupported.

use anyhow::{bail, Context, Result};
use nix::fcntl::AtFlags;
use nix::sys::stat::{fstatat, FileStat};
use std::collections::{BTreeMap, HashSet};
use std::ffi::OsStr;
use std::fs::File;
use std::io::{Read, Seek, Write};
use std::os::fd::AsRawFd;
use std::os::unix::ffi::OsStrExt;
use std::path::Path;
use std::time::Duration;

use crate::context::extract::dialect::{dialect_for_path, DialectSpec};
use crate::context::refresh::excluded;
use crate::fs::safe_fs::{open_safely, safe_open_dirfd};
use crate::git::runner::{run_git_pinned, run_git_pinned_within, GIT_READ_TIMEOUT};

const SYMLINK_MODE: &str = "120000";
const GITLINK_MODE: &str = "160000";

/// Extension key under which a path that is not valid UTF-8 is counted.
const NON_UTF8_EXTENSION: &str = "(non-utf8)";

/// Path segments that mark third-party code.
const VENDORED_SEGMENTS: &[&str] = &[
    "vendor",
    "third_party",
    "third-party",
    "node_modules",
    "bower_components",
    "Pods",
];

/// Header text that marks a machine-written file.
const GENERATED_MARKERS: &[&[u8]] = &[
    b"@generated",
    b"DO NOT EDIT",
    b"Code generated",
    b"autogenerated",
];

/// How many leading bytes are scanned for a generated marker.
const MARKER_SCAN_BYTES: u64 = 1024;

/// What the index records for a path. Only a regular file is ever opened.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) enum EntryKind {
    Regular,
    Symlink,
    Gitlink,
}

pub(super) struct Tracked {
    /// The repo-relative path; lossily decoded when `non_utf8` is set.
    pub path: String,
    pub kind: EntryKind,
    /// The exact path bytes when the path is not valid UTF-8. Such a path is
    /// only ever sized and counted as unsupported, never parsed.
    pub non_utf8: Option<Vec<u8>>,
}

impl Tracked {
    /// The path beneath the checkout root.
    fn relative_path(&self) -> &Path {
        match &self.non_utf8 {
            Some(raw) => Path::new(OsStr::from_bytes(raw)),
            None => Path::new(&self.path),
        }
    }
}

#[derive(Debug, Clone, Copy)]
pub(super) enum Class {
    Excluded,
    Vendored,
    Generated,
    Eligible(&'static DialectSpec),
    Unsupported,
}

pub(super) struct Classified {
    pub class: Class,
    /// Size of a regular file; 0 for a symlink, gitlink or other non-file.
    pub bytes: u64,
    /// Lowercase extension, `(none)` when the name has none.
    pub extension: String,
}

/// Paths git marks `linguist-vendored` or `linguist-generated`.
#[derive(Default)]
pub(super) struct Attributes {
    vendored: HashSet<String>,
    generated: HashSet<String>,
}

/// Every tracked path of `root` with its entry kind, from
/// `git ls-files -s -z`. Records read `<mode> <oid> <stage>\t<path>`; the path
/// is everything after the first tab, so spaces and non-ASCII survive. A path
/// that is not UTF-8 is kept with its raw bytes.
pub(super) fn tracked_files(root: &Path) -> Result<Vec<Tracked>> {
    let output = run_git_pinned(&["ls-files", "-s", "-z"], None, root)?;
    if !output.status.success() {
        bail!(
            "git ls-files failed in {}: {}",
            root.display(),
            String::from_utf8_lossy(&output.stderr).trim()
        );
    }
    // A conflicted path appears once per stage; the map, keyed by the raw path
    // bytes, keeps one entry.
    let mut entries = BTreeMap::new();
    for record in output.stdout.split(|byte| *byte == 0) {
        let Some(tab) = record.iter().position(|byte| *byte == b'\t') else {
            continue;
        };
        let (metadata, path) = (&record[..tab], &record[tab + 1..]);
        let kind = match metadata.split(|byte| byte.is_ascii_whitespace()).next() {
            Some(mode) if mode == SYMLINK_MODE.as_bytes() => EntryKind::Symlink,
            Some(mode) if mode == GITLINK_MODE.as_bytes() => EntryKind::Gitlink,
            _ => EntryKind::Regular,
        };
        entries.insert(path.to_vec(), kind);
    }
    Ok(entries
        .into_iter()
        .map(|(raw, kind)| match String::from_utf8(raw) {
            Ok(path) => Tracked {
                path,
                kind,
                non_utf8: None,
            },
            Err(error) => Tracked {
                path: String::from_utf8_lossy(error.as_bytes()).into_owned(),
                kind,
                non_utf8: Some(error.into_bytes()),
            },
        })
        .collect())
}

/// Ask git once for the attributes of every path in `paths`.
///
/// Paths go through a file on stdin, never argv, so thousands of long paths
/// stay under `ARG_MAX`. A file has no writer to stall against a full stdout
/// pipe, and the deadline covers the whole call: git blocked reading a
/// `.gitattributes` that is a FIFO is killed when it runs out.
pub(super) fn attributes(root: &Path, paths: &[&str]) -> Result<Attributes> {
    attributes_within(root, paths, GIT_READ_TIMEOUT)
}

/// [`attributes`] under an explicit `timeout`.
pub(super) fn attributes_within(
    root: &Path,
    paths: &[&str],
    timeout: Duration,
) -> Result<Attributes> {
    if paths.is_empty() {
        return Ok(Attributes::default());
    }
    let args = [
        "check-attr",
        "--stdin",
        "-z",
        "linguist-vendored",
        "linguist-generated",
    ];
    let output = run_git_pinned_within(&args, Some(path_list(paths)?), root, timeout)?;
    if !output.status.success() {
        bail!(
            "git check-attr failed in {}: {}",
            root.display(),
            String::from_utf8_lossy(&output.stderr).trim()
        );
    }
    Ok(parse_attributes(&output.stdout))
}

/// `paths`, each NUL-terminated, in an unnamed temp file rewound for reading.
fn path_list(paths: &[&str]) -> Result<File> {
    let mut bytes = Vec::new();
    for path in paths {
        bytes.extend_from_slice(path.as_bytes());
        bytes.push(0);
    }
    let mut list = tempfile::tempfile().context("Failed to create the check-attr path list")?;
    list.write_all(&bytes)
        .and_then(|()| list.rewind())
        .context("Failed to write the check-attr path list")?;
    Ok(list)
}

/// `-z` output is `<path> NUL <attribute> NUL <value> NUL` per pair.
fn parse_attributes(stdout: &[u8]) -> Attributes {
    let mut attributes = Attributes::default();
    let mut fields = stdout.split(|byte| *byte == 0);
    while let (Some(path), Some(name), Some(value)) = (fields.next(), fields.next(), fields.next())
    {
        if !matches!(value, b"set" | b"true") {
            continue;
        }
        let path = String::from_utf8_lossy(path).into_owned();
        match name {
            b"linguist-vendored" => attributes.vendored.insert(path),
            b"linguist-generated" => attributes.generated.insert(path),
            _ => continue,
        };
    }
    attributes
}

/// Classify one tracked path, in the order excluded, vendored, generated,
/// eligible, unsupported. `None` when a regular file is gone from the working
/// tree.
pub(super) fn classify(
    root: &Path,
    tracked: &Tracked,
    attributes: &Attributes,
) -> Option<Classified> {
    let path = tracked.path.as_str();
    let bytes = size_of(root, tracked)?;
    if tracked.non_utf8.is_some() {
        return Some(Classified {
            class: Class::Unsupported,
            bytes,
            extension: NON_UTF8_EXTENSION.to_string(),
        });
    }
    let extension = Path::new(path).extension().map_or_else(
        || "(none)".to_string(),
        |ext| ext.to_string_lossy().to_ascii_lowercase(),
    );
    let class = if excluded(path) {
        Class::Excluded
    } else if is_vendored(path, attributes) {
        Class::Vendored
    } else if tracked.kind != EntryKind::Regular {
        Class::Unsupported
    } else if attributes.generated.contains(path) || has_generated_marker(root, path) {
        Class::Generated
    } else {
        dialect_for_path(Path::new(path)).map_or(Class::Unsupported, Class::Eligible)
    };
    Some(Classified {
        class,
        bytes,
        extension,
    })
}

/// A regular file's size without following a symlink at any path component:
/// the parent directory is opened beneath `root` with every symlink refused,
/// and the name is `fstatat`ed unfollowed. Symlinks and gitlinks are sized 0
/// without touching their targets. `None` when the file is gone, or no longer
/// reachable that way.
fn size_of(root: &Path, tracked: &Tracked) -> Option<u64> {
    if tracked.kind != EntryKind::Regular {
        return Some(0);
    }
    let stat = stat_unfollowed(root, tracked.relative_path()).ok()?;
    let is_file = stat.st_mode & libc::S_IFMT == libc::S_IFREG;
    Some(if is_file {
        u64::try_from(stat.st_size).unwrap_or(0)
    } else {
        0
    })
}

fn stat_unfollowed(root: &Path, relative: &Path) -> Result<FileStat> {
    let root_fd = safe_open_dirfd(root)?;
    let name = relative.file_name().context("tracked path has no name")?;
    let parent = match relative.parent().filter(|dir| !dir.as_os_str().is_empty()) {
        Some(dir) => {
            let flags = libc::O_DIRECTORY | libc::O_RDONLY | libc::O_NONBLOCK;
            open_safely(root_fd.as_raw_fd(), dir, flags, 0)?
        }
        None => root_fd,
    };
    Ok(fstatat(&parent, name, AtFlags::AT_SYMLINK_NOFOLLOW)?)
}

fn is_vendored(path: &str, attributes: &Attributes) -> bool {
    attributes.vendored.contains(path)
        || path
            .split('/')
            .any(|segment| VENDORED_SEGMENTS.contains(&segment))
}

/// Whether the first [`MARKER_SCAN_BYTES`] of the file hold a generated
/// marker. The file is opened beneath `root` with a symlink refused at every
/// component, `O_NONBLOCK`, and read only once `fstat` says it is a regular
/// file, so a link swapped in since enumeration, or a FIFO, is never read.
fn has_generated_marker(root: &Path, path: &str) -> bool {
    let Some(file) = open_regular(root, Path::new(path)) else {
        return false;
    };
    let mut head = Vec::new();
    if file.take(MARKER_SCAN_BYTES).read_to_end(&mut head).is_err() {
        return false;
    }
    GENERATED_MARKERS
        .iter()
        .any(|marker| head.windows(marker.len()).any(|window| window == *marker))
}

fn open_regular(root: &Path, relative: &Path) -> Option<File> {
    let root_fd = safe_open_dirfd(root).ok()?;
    let flags = libc::O_RDONLY | libc::O_NONBLOCK;
    let file = File::from(open_safely(root_fd.as_raw_fd(), relative, flags, 0).ok()?);
    file.metadata().ok()?.is_file().then_some(file)
}

#[cfg(test)]
mod tests;
