//! Enumerating a checkout's tracked files and sorting each into one census
//! class: excluded, vendored, generated, eligible or unsupported.

use anyhow::{bail, Context, Result};
use std::collections::{BTreeMap, HashSet};
use std::ffi::OsStr;
use std::fs::OpenOptions;
use std::io::{Read, Write};
use std::os::unix::ffi::OsStrExt;
use std::os::unix::fs::OpenOptionsExt;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

use crate::context::extract::dialect::{dialect_for_path, DialectSpec};
use crate::context::refresh::excluded;
use crate::git::runner::{run_git, NO_HOOKS_ARGS};

const SYMLINK_MODE: &str = "120000";
const GITLINK_MODE: &str = "160000";

/// Extension key under which a path that is not valid UTF-8 is counted.
const NON_UTF8_EXTENSION: &str = "(non-utf8)";

/// Path segments that mark third-party code.
const VENDORED_SEGMENTS: &[&str] = &[
    "vendor",
    "third_party",
    "third-party",
    "node_modules",
    "bower_components",
    "Pods",
];

/// Header text that marks a machine-written file.
const GENERATED_MARKERS: &[&[u8]] = &[
    b"@generated",
    b"DO NOT EDIT",
    b"Code generated",
    b"autogenerated",
];

/// How many leading bytes are scanned for a generated marker.
const MARKER_SCAN_BYTES: u64 = 1024;

/// What the index records for a path. Only a regular file is ever opened.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) enum EntryKind {
    Regular,
    Symlink,
    Gitlink,
}

pub(super) struct Tracked {
    /// The repo-relative path; lossily decoded when `non_utf8` is set.
    pub path: String,
    pub kind: EntryKind,
    /// The exact path bytes when the path is not valid UTF-8. Such a path is
    /// only ever sized and counted as unsupported, never parsed.
    pub non_utf8: Option<Vec<u8>>,
}

impl Tracked {
    fn full_path(&self, root: &Path) -> PathBuf {
        match &self.non_utf8 {
            Some(raw) => root.join(OsStr::from_bytes(raw)),
            None => root.join(&self.path),
        }
    }
}

#[derive(Debug, Clone, Copy)]
pub(super) enum Class {
    Excluded,
    Vendored,
    Generated,
    Eligible(&'static DialectSpec),
    Unsupported,
}

pub(super) struct Classified {
    pub class: Class,
    /// Size of a regular file; 0 for a symlink, gitlink or other non-file.
    pub bytes: u64,
    /// Lowercase extension, `(none)` when the name has none.
    pub extension: String,
}

/// Paths git marks `linguist-vendored` or `linguist-generated`.
#[derive(Default)]
pub(super) struct Attributes {
    vendored: HashSet<String>,
    generated: HashSet<String>,
}

/// Every tracked path of `root` with its entry kind, from
/// `git ls-files -s -z`. Records read `<mode> <oid> <stage>\t<path>`; the path
/// is everything after the first tab, so spaces and non-ASCII survive. A path
/// that is not UTF-8 is kept with its raw bytes.
pub(super) fn tracked_files(root: &Path) -> Result<Vec<Tracked>> {
    let output = run_git(&["ls-files", "-s", "-z"], root)?;
    if !output.status.success() {
        bail!(
            "git ls-files failed in {}: {}",
            root.display(),
            String::from_utf8_lossy(&output.stderr).trim()
        );
    }
    // A conflicted path appears once per stage; the map, keyed by the raw path
    // bytes, keeps one entry.
    let mut entries = BTreeMap::new();
    for record in output.stdout.split(|byte| *byte == 0) {
        let Some(tab) = record.iter().position(|byte| *byte == b'\t') else {
            continue;
        };
        let (metadata, path) = (&record[..tab], &record[tab + 1..]);
        let kind = match metadata.split(|byte| byte.is_ascii_whitespace()).next() {
            Some(mode) if mode == SYMLINK_MODE.as_bytes() => EntryKind::Symlink,
            Some(mode) if mode == GITLINK_MODE.as_bytes() => EntryKind::Gitlink,
            _ => EntryKind::Regular,
        };
        entries.insert(path.to_vec(), kind);
    }
    Ok(entries
        .into_iter()
        .map(|(raw, kind)| match String::from_utf8(raw) {
            Ok(path) => Tracked {
                path,
                kind,
                non_utf8: None,
            },
            Err(error) => Tracked {
                path: String::from_utf8_lossy(error.as_bytes()).into_owned(),
                kind,
                non_utf8: Some(error.into_bytes()),
            },
        })
        .collect())
}

/// Ask git once for the attributes of every path in `paths`.
///
/// Paths go through stdin, never argv, so thousands of long paths stay under
/// `ARG_MAX`. A separate thread writes stdin while this thread drains stdout
/// (and stderr), so neither pipe can fill and stall git.
pub(super) fn attributes(root: &Path, paths: &[&str]) -> Result<Attributes> {
    if paths.is_empty() {
        return Ok(Attributes::default());
    }
    let mut child = Command::new("git")
        .args(NO_HOOKS_ARGS)
        .args([
            "check-attr",
            "--stdin",
            "-z",
            "linguist-vendored",
            "linguist-generated",
        ])
        .env("LC_ALL", "C")
        .env("LANG", "C")
        .current_dir(root)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .context("Failed to execute: git check-attr")?;
    let mut stdin = child.stdin.take().context("git check-attr has no stdin")?;
    let output = std::thread::scope(|scope| {
        scope.spawn(move || {
            for path in paths {
                if stdin.write_all(path.as_bytes()).is_err() || stdin.write_all(&[0]).is_err() {
                    break;
                }
            }
            // `stdin` drops here: git reads until EOF before it answers.
        });
        child.wait_with_output()
    })?;
    if !output.status.success() {
        bail!(
            "git check-attr failed in {}: {}",
            root.display(),
            String::from_utf8_lossy(&output.stderr).trim()
        );
    }
    Ok(parse_attributes(&output.stdout))
}

/// `-z` output is `<path> NUL <attribute> NUL <value> NUL` per pair.
fn parse_attributes(stdout: &[u8]) -> Attributes {
    let mut attributes = Attributes::default();
    let mut fields = stdout.split(|byte| *byte == 0);
    while let (Some(path), Some(name), Some(value)) = (fields.next(), fields.next(), fields.next())
    {
        if !matches!(value, b"set" | b"true") {
            continue;
        }
        let path = String::from_utf8_lossy(path).into_owned();
        match name {
            b"linguist-vendored" => attributes.vendored.insert(path),
            b"linguist-generated" => attributes.generated.insert(path),
            _ => continue,
        };
    }
    attributes
}

/// Classify one tracked path, in the order excluded, vendored, generated,
/// eligible, unsupported. `None` when a regular file is gone from the working
/// tree.
pub(super) fn classify(
    root: &Path,
    tracked: &Tracked,
    attributes: &Attributes,
) -> Option<Classified> {
    let path = tracked.path.as_str();
    let bytes = size_of(root, tracked)?;
    if tracked.non_utf8.is_some() {
        return Some(Classified {
            class: Class::Unsupported,
            bytes,
            extension: NON_UTF8_EXTENSION.to_string(),
        });
    }
    let extension = Path::new(path).extension().map_or_else(
        || "(none)".to_string(),
        |ext| ext.to_string_lossy().to_ascii_lowercase(),
    );
    let class = if excluded(path) {
        Class::Excluded
    } else if is_vendored(path, attributes) {
        Class::Vendored
    } else if tracked.kind != EntryKind::Regular {
        Class::Unsupported
    } else if attributes.generated.contains(path) || has_generated_marker(root, path) {
        Class::Generated
    } else {
        dialect_for_path(Path::new(path)).map_or(Class::Unsupported, Class::Eligible)
    };
    Some(Classified {
        class,
        bytes,
        extension,
    })
}

/// A regular file's size from `symlink_metadata`, so a link is never followed.
/// Symlinks and gitlinks are sized 0 without touching their targets.
fn size_of(root: &Path, tracked: &Tracked) -> Option<u64> {
    if tracked.kind != EntryKind::Regular {
        return Some(0);
    }
    let metadata = std::fs::symlink_metadata(tracked.full_path(root)).ok()?;
    Some(if metadata.file_type().is_file() {
        metadata.len()
    } else {
        0
    })
}

fn is_vendored(path: &str, attributes: &Attributes) -> bool {
    attributes.vendored.contains(path)
        || path
            .split('/')
            .any(|segment| VENDORED_SEGMENTS.contains(&segment))
}

/// Whether the first [`MARKER_SCAN_BYTES`] of the file hold a generated
/// marker. The file is opened `O_NOFOLLOW | O_NONBLOCK` and only after
/// `symlink_metadata` says it is a regular file, so a link swapped in since
/// enumeration, or a FIFO, is never read.
fn has_generated_marker(root: &Path, path: &str) -> bool {
    let full = root.join(path);
    let is_file = std::fs::symlink_metadata(&full).is_ok_and(|m| m.file_type().is_file());
    if !is_file {
        return false;
    }
    let Ok(file) = OpenOptions::new()
        .read(true)
        .custom_flags(libc::O_NOFOLLOW | libc::O_NONBLOCK)
        .open(&full)
    else {
        return false;
    };
    let mut head = Vec::new();
    if file.take(MARKER_SCAN_BYTES).read_to_end(&mut head).is_err() {
        return false;
    }
    GENERATED_MARKERS
        .iter()
        .any(|marker| head.windows(marker.len()).any(|window| window == *marker))
}
