use std::collections::BTreeSet;
use std::fs;
use std::path::Path;
use std::process::Command;

use tempfile::TempDir;

use super::subprojects::SubprojectIndex;
use super::*;
use crate::context::graph_store::FileEntry;
use crate::context::source_graph::Span;

fn git(root: &Path, args: &[&str]) {
    let output = Command::new("git")
        .args(args)
        .current_dir(root)
        .env("GIT_CONFIG_GLOBAL", root.join(".loom-test-no-global"))
        .env("GIT_CONFIG_SYSTEM", root.join(".loom-test-no-system"))
        .env("GIT_CONFIG_NOSYSTEM", "1")
        .output()
        .expect("spawn git");
    assert!(
        output.status.success(),
        "git {args:?} failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
}

/// A committed repo holding `files`. Nothing is created under `.loom/`.
fn repo(files: &[(&str, &str)]) -> TempDir {
    let temp = tempfile::tempdir().expect("tempdir");
    let root = temp.path();
    git(root, &["init", "-q"]);
    git(root, &["config", "user.name", "t"]);
    git(root, &["config", "user.email", "t@t"]);
    for (path, body) in files {
        let full = root.join(path);
        fs::create_dir_all(full.parent().expect("parent")).expect("create dirs");
        fs::write(full, body).expect("write file");
    }
    git(root, &["add", "-A"]);
    git(root, &["commit", "-q", "-m", "seed"]);
    temp
}

fn census(root: &Path) -> CensusReport {
    let options = CensusOptions {
        roots: vec![root.to_path_buf()],
    };
    run(&options, None).expect("census")
}

fn counts(count: Count) -> (u64, u64) {
    (count.files, count.bytes)
}

/// The resolved graph a build of `paths` under `root` would hold.
fn graph_of(root: &Path, paths: &[&str]) -> ResolvedGraph {
    let extractors = registry();
    let files = paths
        .iter()
        .map(|path| {
            let bytes = fs::read(root.join(path)).expect("read fixture");
            let extraction = extract_file(&extractors, Path::new(path), &bytes);
            (
                path.to_string(),
                FileEntry::from_extraction(&bytes, extraction),
            )
        })
        .collect();
    ResolvedGraph {
        base_revision: String::new(),
        overlaid: BTreeSet::new(),
        files,
    }
}

#[test]
fn classifies_every_class_and_totals_bytes() {
    let temp = repo(&[
        ("src/a.rs", "pub fn a() {}\n"),
        ("vendor/v.rs", "pub fn v() {}\n"),
        ("src/gen.rs", "// @generated\npub fn g() {}\n"),
        ("notes.xyz", "hello\n"),
        ("target/t.rs", "pub fn t() {}\n"),
        ("lib/attr_vendored.rs", "pub fn x() {}\n"),
        ("lib/attr_generated.rs", "pub fn y() {}\n"),
        (
            ".gitattributes",
            "lib/attr_vendored.rs linguist-vendored\nlib/attr_generated.rs linguist-generated\n",
        ),
    ]);
    let report = census(temp.path());

    assert_eq!(counts(report.totals.eligible), (1, 14));
    assert_eq!(counts(report.totals.vendored), (2, 28));
    assert_eq!(counts(report.totals.generated), (2, 42));
    assert_eq!(counts(report.totals.excluded), (1, 14));
    // notes.xyz and .gitattributes.
    assert_eq!(report.totals.unsupported.files, 2);
    assert_eq!(report.totals, report.roots[0].totals);
}

#[test]
fn every_generated_marker_is_found_only_in_the_first_kilobyte() {
    let late = format!("{}\n// @generated\n", "x".repeat(1100));
    let temp = repo(&[
        ("a.rs", "// @generated\n"),
        ("b.rs", "// DO NOT EDIT\n"),
        ("c.go", "// Code generated by tool.\n"),
        ("d.py", "# autogenerated\n"),
        ("e.rs", late.as_str()),
    ]);
    let report = census(temp.path());

    assert_eq!(report.totals.generated.files, 4);
    assert_eq!(
        report.totals.eligible.files, 1,
        "e.rs marks past 1024 bytes"
    );
}

#[test]
fn paths_with_spaces_and_non_ascii_are_classified() {
    let temp = repo(&[
        ("src dir/naïve file.rs", "pub fn a() {}\n"),
        ("src dir/日本.rs", "pub fn b() {}\n"),
    ]);

    assert_eq!(counts(census(temp.path()).totals.eligible), (2, 28));
}

#[test]
fn groups_files_by_nearest_manifest() {
    let temp = repo(&[
        ("Cargo.toml", ""),
        ("src/a.rs", "pub fn a() {}\n"),
        ("web/package.json", "{}\n"),
        ("web/app.ts", "export const a = 1;\n"),
        ("web/deep/b.ts", "export const b = 2;\n"),
        ("crates/core/Cargo.toml", ""),
        ("crates/core/src/l.rs", "pub fn l() {}\n"),
    ]);
    let report = census(temp.path());
    let by_path: BTreeMap<&str, &SubprojectCensus> = report.roots[0]
        .subprojects
        .iter()
        .map(|subproject| (subproject.path.as_str(), subproject))
        .collect();

    assert_eq!(
        by_path.keys().copied().collect::<Vec<_>>(),
        vec![".", "crates/core", "web"]
    );
    assert_eq!(by_path["web"].by_dialect["typescript"].files, 2);
    assert_eq!(by_path["crates/core"].by_dialect["rust"].files, 1);
    assert_eq!(by_path["."].by_dialect["rust"].files, 1);
}

#[test]
fn subproject_index_falls_back_to_the_root_and_reads_suffix_manifests() {
    let index = SubprojectIndex::new(["app/App.csproj", "svc/go.mod", "lone.rs"]);

    assert_eq!(index.assign("app/Program.cs"), "app");
    assert_eq!(index.assign("svc/pkg/x.go"), "svc");
    assert_eq!(index.assign("lone.rs"), ".");
    assert_eq!(index.assign("other/x.rs"), ".");
}

#[cfg(unix)]
#[test]
fn census_never_follows_a_symlink() {
    let temp = repo(&[("a.rs", "pub fn a() {}\n")]);
    let root = temp.path();
    std::os::unix::fs::symlink("/dev/zero", root.join("x.rs")).expect("symlink");
    git(root, &["add", "x.rs"]);
    git(root, &["commit", "-q", "-m", "link"]);

    let report = census(root);

    assert_eq!(counts(report.totals.unsupported), (1, 0));
    assert_eq!(counts(report.totals.eligible), (1, 14));
}

#[test]
fn a_graph_root_reads_coverage_from_the_graph() {
    let temp = repo(&[
        ("a.rs", "pub fn a() {}\n"),
        ("b.rs", "pub fn b() {}\n"),
        ("c.rs", "pub fn c() {}\n"),
    ]);
    let mut graph = graph_of(temp.path(), &["a.rs", "b.rs"]);
    graph.files.get_mut("b.rs").expect("b.rs").coverage = FileCoverage::ParseError {
        span: Span::default(),
        detail: "boom".to_string(),
    };
    let options = CensusOptions::default();

    let report = run(&options, Some((temp.path(), &graph))).expect("census");

    let root = &report.roots[0];
    let rust = &root.subprojects[0].by_dialect["rust"];
    assert_eq!(root.coverage_source, CoverageSource::Graph);
    assert!(root.parse.is_none());
    assert_eq!(
        (rust.files, rust.symbol_files, rust.parse_errors),
        (3, 1, 1)
    );
    assert_eq!((rust.bytes, rust.symbol_bytes), (42, 14));
    assert_eq!(rust.extractor, "available");
    assert_eq!(counts(root.symbol_level()), (1, 14));
}

#[test]
fn an_empty_graph_falls_back_to_in_memory_extraction() {
    let temp = repo(&[("a.rs", "pub fn a() {}\n")]);
    let graph = graph_of(temp.path(), &[]);

    let report = run(&CensusOptions::default(), Some((temp.path(), &graph))).expect("census");

    let root = &report.roots[0];
    assert_eq!(root.coverage_source, CoverageSource::InMemory);
    assert_eq!(counts(root.symbol_level()), (1, 14));
}

#[test]
fn another_root_is_extracted_in_memory_without_writing() {
    let current = repo(&[("a.rs", "pub fn a() {}\n")]);
    let other = repo(&[("b.rs", "pub fn b() {}\n"), ("c.rs", "pub fn c() {}\n")]);
    let graph = graph_of(current.path(), &["a.rs"]);
    let options = CensusOptions {
        roots: vec![current.path().to_path_buf(), other.path().to_path_buf()],
    };

    let report = run(&options, Some((current.path(), &graph))).expect("census");

    assert_eq!(report.roots[0].coverage_source, CoverageSource::Graph);
    let second = &report.roots[1];
    assert_eq!(second.coverage_source, CoverageSource::InMemory);
    let parse = second.parse.expect("in-memory root reports parse stats");
    assert_eq!((parse.files_parsed, parse.bytes_read), (2, 28));
    assert_eq!(counts(second.symbol_level()), (2, 28));
    assert_eq!(counts(report.totals.eligible), (3, 42));
    assert!(
        !other.path().join(".loom").exists(),
        "a census must not create .loom/ under a root it inspects"
    );
}

#[test]
fn a_root_that_is_not_a_work_tree_is_an_error() {
    let temp = tempfile::tempdir().expect("tempdir");
    let options = CensusOptions {
        roots: vec![temp.path().to_path_buf()],
    };

    assert!(run(&options, None).is_err());
    assert!(run(&CensusOptions::default(), None).is_err());
}

#[test]
fn json_carries_the_schema_and_class_objects() {
    let temp = repo(&[("a.rs", "pub fn a() {}\n"), ("n.xyz", "hi\n")]);
    let report = census(temp.path());

    let json = serde_json::to_value(&report).expect("serialize");

    assert_eq!(json["schema"], "loom-census/1");
    assert_eq!(json["totals"]["eligible"]["files"], 1);
    assert_eq!(json["totals"]["eligible"]["bytes"], 14);
    for class in ["excluded", "vendored", "generated", "unsupported"] {
        assert!(json["totals"][class]["bytes"].is_u64(), "totals.{class}");
    }
    let subproject = &json["roots"][0]["subprojects"][0];
    assert_eq!(subproject["by_dialect"]["rust"]["files"], 1);
    assert_eq!(subproject["unsupported_by_extension"]["xyz"]["bytes"], 3);
}

#[test]
fn display_lists_totals_dialects_and_unsupported_extensions() {
    let temp = repo(&[
        ("a.rs", "pub fn a() {}\n"),
        ("vendor/v.rs", "pub fn v() {}\n"),
        ("big.xyz", "0123456789\n"),
        ("small.abc", "x\n"),
    ]);
    let text = census(temp.path()).to_string();

    assert!(text.contains("rust  files 1  bytes 14"), "{text}");
    assert!(text.contains("vendored 1 files 14 bytes"), "{text}");
    assert!(text.contains("excluded roots: .loom"), "{text}");
    let xyz = text.find("xyz  1 files  11 bytes").expect("xyz row");
    let abc = text.find("abc  1 files  2 bytes").expect("abc row");
    assert!(xyz < abc, "largest extension first: {text}");
}

#[test]
fn census_handles_thousands_of_long_paths() {
    const FILES: usize = 3000;
    let deep: Vec<String> = (0..13)
        .map(|level| format!("d{level:02}{}", "x".repeat(57)))
        .collect();
    let dir = deep.join("/");
    let paths: Vec<String> = (0..FILES).map(|n| format!("{dir}/f{n}.rs")).collect();
    let total: usize = paths.iter().map(String::len).sum();
    assert!(total > 2 * 1024 * 1024, "paths total {total} bytes");
    let files: Vec<(&str, &str)> = paths
        .iter()
        .map(|path| (path.as_str(), "pub fn f() {}\n"))
        .collect();
    let temp = repo(&files);

    let report = census(temp.path());

    assert_eq!(report.totals.eligible.files, FILES as u64);
}

#[cfg(unix)]
#[test]
fn a_non_utf8_path_is_counted_once_as_unsupported() {
    use std::ffi::OsStr;
    use std::os::unix::ffi::OsStrExt;

    let temp = repo(&[("a.rs", "pub fn a() {}\n")]);
    let root = temp.path();
    fs::write(
        root.join(OsStr::from_bytes(b"caf\xe9.rs")),
        "pub fn b() {}\n",
    )
    .expect("write");
    git(root, &["add", "-A"]);
    git(root, &["commit", "-q", "-m", "non-utf8"]);

    let report = census(root);
    let totals = &report.totals;

    assert_eq!(counts(totals.eligible), (1, 14));
    assert_eq!(counts(totals.unsupported), (1, 14));
    let file_count = totals.eligible.files
        + totals.excluded.files
        + totals.vendored.files
        + totals.generated.files
        + totals.unsupported.files;
    assert_eq!(file_count, 2, "every tracked file is counted");
    let by_extension = &report.roots[0].subprojects[0].unsupported_by_extension;
    assert_eq!(by_extension["(non-utf8)"].files, 1);
}
